services:
  - type: web
    name: auto-media-save
    env: node
    repo: sajid3377/auto-media-save
    branch: main
    plan: free
    # Build and start
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: RAPIDAPI_KEY
        # set via Render dashboard
        value: ""
      - key: RAPIDAPI_HOST
        value: "allmedia-downloader.p.rapidapi.com"
      - key: RAPIDAPI_PATH
        value: "/universal"
      - key: PORT
        value: "3000"
    healthCheckPath: "/"
    autoDeploy: true
